CREATE DATABASE IF NOT EXISTS lab_mysql;
USE lab_mysql;

DROP TABLE IF EXISTS Cars;
CREATE TABLE CARS(
    Cars_ID INT AUTO_INCREMENT PRIMARY KEY,
	VIN VARCHAR(25),
    Manufacturer VARCHAR(15),
    model VARCHAR(30),
    Year YEAR,
    Color VARCHAR(10));
    
 DROP TABLE IF EXISTS Customers;
 CREATE TABLE CUSTOMERS(
	Customer_ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(15),
    Phone_number INT,
    Email VARCHAR(25),
    Address VARCHAR(50),
    City VARCHAR(15),
    State VARCHAR(15),
    Country VARCHAR(15),
    Zip_Postal_code VARCHAR(10));
    
DROP TABLE IF EXISTS Sales_persons;
CREATE TABLE SALES_PERSONS(
	Staff_ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(15),
    Store VARCHAR(15));
    
DROP TABLE IF EXISTS Invoices;
CREATE TABLE INVOICES(
	Invoice_ID INT AUTO_INCREMENT PRIMARY KEY,
    Invoice_number INT,
    Date DATE,
    Cars_ID INT,
    FOREIGN KEY (Cars_ID) REFERENCES CARS(Cars_ID),
    Customer_ID INT,
    FOREIGN KEY (Customer_ID) REFERENCES CUSTOMERS(Customer_ID),
    Staff_ID INT,
    FOREIGN KEY (Staff_ID) REFERENCES SALES_PERSONS(Staff_ID)
    );
    
SELECT * FROM CARS;
SELECT * FROM CUSTOMERS;
SELECT * FROM SALES_PERSONS;
SELECT * FROM INVOICES;    
